name: booknest_fe
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: 2.2.3
  google_fonts: ^6.2.0
  animated_toggle_switch: ^0.8.3
  http: ^1.2.2
  dropdown_button2: ^2.3.9
  animated_bottom_navigation_bar: ^1.3.3
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  sign_in_button: ^3.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
