// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIiSRwlV1ksKIiuDbuoHqYmfAtuqb2gR8',
    appId: '1:421818058869:web:f05094fa6068c4c7f8d03c',
    messagingSenderId: '421818058869',
    projectId: 'booknest-c07a1',
    authDomain: 'booknest-c07a1.firebaseapp.com',
    storageBucket: 'booknest-c07a1.appspot.com',
    measurementId: 'G-PSQ9XDRQS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9SGiaTIKP0Xs7EUVY645DkugJo1F5cMw',
    appId: '1:421818058869:android:142f3b5c86582b17f8d03c',
    messagingSenderId: '421818058869',
    projectId: 'booknest-c07a1',
    storageBucket: 'booknest-c07a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqgA9V6lj16WYao5tCMiFcMQHtKBM9y4w',
    appId: '1:421818058869:ios:cea1b9c7abb566edf8d03c',
    messagingSenderId: '421818058869',
    projectId: 'booknest-c07a1',
    storageBucket: 'booknest-c07a1.appspot.com',
    androidClientId: '421818058869-5a8ck1noo4kuj44144bodp9a65umg3vk.apps.googleusercontent.com',
    iosClientId: '421818058869-6oed9j9vm8ti3uhhk9mqfm7995u4vuqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.booknestFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqgA9V6lj16WYao5tCMiFcMQHtKBM9y4w',
    appId: '1:421818058869:ios:cea1b9c7abb566edf8d03c',
    messagingSenderId: '421818058869',
    projectId: 'booknest-c07a1',
    storageBucket: 'booknest-c07a1.appspot.com',
    androidClientId: '421818058869-5a8ck1noo4kuj44144bodp9a65umg3vk.apps.googleusercontent.com',
    iosClientId: '421818058869-6oed9j9vm8ti3uhhk9mqfm7995u4vuqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.booknestFe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIiSRwlV1ksKIiuDbuoHqYmfAtuqb2gR8',
    appId: '1:421818058869:web:2a0bfc011ab72279f8d03c',
    messagingSenderId: '421818058869',
    projectId: 'booknest-c07a1',
    authDomain: 'booknest-c07a1.firebaseapp.com',
    storageBucket: 'booknest-c07a1.appspot.com',
    measurementId: 'G-GWFWFV32CT',
  );
}
